### ISSUE TITLE
Renewing certs

### ISSUE THREAD

**Issue by bencooling** [AnalogJ/aws-api-gateway-letsencrypt#1]
Awesome work thank you!
What would you recommend for automatically renewing the created certificates?
I wasn't sure whether this would be compatible with a lambda solution like [lambda-letsencrypt](https://github.com/ubergeek42/lambda-letsencrypt)

**Comment by AnalogJ** [comment]
Hey Ben,
I don't know if that method to renew letsencrypt certs will work as it
assumes cloudfront in front of s3. However you could probably modify it to
make it work with an api gateway.

**Comment by bencooling** [comment]
Thanks for the reply @AnalogJ.

Reading over the source code I see:
`#TODO: we should update the existing certificates with the new ones here, but the cli doesnt seem to support that yet.`

Does that mean if the cert required renewal you would just run the docker image again after deleting the custom domain in aws? i.e.

1. `docker run ...`
2. Cert approaches expiration; delete the custom domain in aws & `docker run ...`

**Comment by geoffdutton** [comment]
@bencooling In #2 I modified the python script to print out the key, cert, and chain as a temp workaround for API Gateway.

**Comment by AnalogJ** [comment]
This should be fixed now. I merged in some of @s3than 's changes. 

The certs are now stored in Amazon Certificate Manager, and are updated automatically if they are going to expire in the next 10 days.
